sudo: false
language: python
env:
  - DJANGO=2.0 TEST_DIR=jalali_test_2_0
  - DJANGO=2.0.2 TEST_DIR=jalali_test_2_0
  - DJANGO=2.2.3 TEST_DIR=jalali_test_2_0
python:
  - 3.4
  - 3.6
install:
  - pip install -q Django==$DJANGO
  - pip install jdatetime pytz
before_script:
  - export PYTHONPATH=$PYTHONPATH:$(pwd)
script:
  - cd $TEST_DIR
  - python manage.py test
  - cd ..
  - python setup.py sdist
  - pip install dist/django-jalali*
